services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  # Register DataFixtures for test environment
  Tourze\ProductAutoDownBundle\DataFixtures\:
    resource: '../../DataFixtures/'